### ISSUE TITLE
process _read is dropping methylation events on reads mapping to the reverse strand (16)

### ISSUE THREAD

**Issue by mitomac** [lidaof/modbedtools#1]
I have two bam files :

watson_read.bam which contains one read with SAM flag 0 
crick_read.bam which contains one read with SAM flag 16.    

Both BAM files have  MM:Z:A+a. and  ML:B:C,  m6a methylation positions and quality scores.

!modbedtools bam2mod -c .6 -b A watson_read.bam -o watson_read  --> generates a correct modbed file 

!modbedtools bam2mod -c .6 -b A crick_read.bam -o crick_read --> generates an empty modbed file

```
        if base == 'A':
            modbase_key = ('T', 1, 'a') if read.is_reverse else ('A', 0, 'a')
        if modbase_key not in read.modified_bases:
            return []
```
walking through the code, `modbase_key = ('T',1,'a')`  is set correctly when read.is_reverse (16)

However, when `modbase_key=('T',1,'a')`  this does not match `read.modified_bases` which returns ('A', 1, 'a')  and empty data is returned.

**Comment by lidaof** [comment]
Hi @mitomac thanks for reporting this issue, possible you can share a small fraction of both the bam files to me? we probably need apply some patch to the code but would like to test on your files as well.

**Comment by mitomac** [comment]
Thanks for the prompt reply. Here are two toy bam files each with a watson
(0) or crick read (16)

And the command I used.

modbedtools bam2mod -c .6 -b A watson_read.bam -o watson_read
modbedtools bam2mod -c .6 -b A crick_read.bam -o crick_read


I also noticed that when using the addbg command that for reads near the
telomere and which might extend past the telomere that there can be an
indexing error.   So I added a simple sanity check to the addbg function.
This might only be an issue in the smaller s. cerevisiae genome and might
be a function of how the repetitive telomeres are present and accounted for
in the genome file.

for x in range(start, end + 1):
               if x >= len(s):  # Check if x exceeds the chromosome length
                   continue  # Skip if it does

Cheers!

Dave

**Comment by lidaof** [comment]
Hi @mitomac thanks for the reply, i assume the here should be a link? :) 

Bye the way, possible you can try change that line:
```
modbase_key = ('T', 1, 'a') if read.is_reverse else ('A', 0, 'a')
```

to

```
modbase_key = ('T', 1, 'a') if read.is_reverse else ('A', 1, 'a')
```

see if it works for both strand bams? (from what you described?)

also thanks for the sanity check for the length issue.
If above change works I would like to invite you to send a PR, then we can merge your contributions to this tool.
Thank you!

**Comment by mitomac** [comment]
oops -- my bad.  damn computers.  the bam files are attached.  will try the
fix shortly.

**Comment by lidaof** [comment]
Hi @mitomac, would like to follow up on this issue see if the fix works? I think github might remove your attachment :)

**Comment by mitomac** [comment]
My apologies for the delay -- day job got in the way.  :)

I  forked your repository, added the test bam files, and the sanity check
for length.  Unfortunately, your suggested change didn't work and
returned empty files for both 0 and 16 reads.

> Bye the way, possible you can try change that line:
>
> modbase_key = ('T', 1, 'a') if read.is_reverse else ('A', 0, 'a')
>
> to
>
> modbase_key = ('T', 1, 'a') if read.is_reverse else ('A', 1, 'a')
>
>
Here is the repository with the test bam files.
https://github.com/mitomac/modbedtools

Best,

Dave

**Comment by lidaof** [comment]
Hi @mitomac David, sorry for the delay, apparently the key should be ('A', 1, 0), my bad...
I have pushed a new version, also included your length check, which should fix this:
`pip install modbedtools==0.1.6`
Thank you!
